version: '0.2'
language: en
allowCompoundWords: true
useGitignore: true
gitignoreRoot: .
ignorePaths:
  - '**/*.{png,jpg,jpeg,gif,svg,icns}'
  - '**/*.min.*'
  - 'pnpm-lock.yaml'
words:
  - COEP
  - eslint
  - haroonwaves
  - Hwaci
  - icns
  - indexeddb
  - myapp
  - opfs
  - sahpool
  - serializability
  - tsbuildinfo
  - tsconfig
  - tseslint
  - typecheck
dictionaries:
  - css
  - html
  - node
  - npm
  - typescript
  - rust
  - rust-common
  - companies
  - misc
