import { defineConfig, type Plugin } from 'vite';
import { resolve } from 'path';
import { fileURLToPath } from 'url';
import { rmSync } from 'fs';
import dts from 'vite-plugin-dts';

const __dirname = fileURLToPath(new URL('.', import.meta.url));

// Plugin to clean up extra assets generated by @sqlite.org/sqlite-wasm
function cleanupAssets(): Plugin {
	return {
		name: 'cleanup-assets',
		closeBundle() {
			// Remove the assets folder containing duplicate SQLite workers
			// Everything is inlined via ?worker&inline, so these aren't needed
			try {
				rmSync(resolve(__dirname, 'dist/assets'), { recursive: true, force: true });
			} catch {
				// Ignore if folder doesn't exist
			}
		},
	};
}

export default defineConfig({
	root: '.', // Root directory for dev server
	plugins: [dts({ rollupTypes: true }), cleanupAssets()],
	build: {
		lib: {
			// Only export the main entry - worker is inlined via ?worker&inline
			entry: resolve(__dirname, 'src/index.ts'),
			formats: ['es'],
			fileName: () => 'index.js',
		},
		rollupOptions: {
			output: {
				// Prevent code splitting - everything in one file
				manualChunks: undefined,
				inlineDynamicImports: true,
			},
		},
		target: 'es2022',
		outDir: 'dist',
		emptyOutDir: true,
		// Disable source maps for smaller production builds
		sourcemap: false,
		// Minify for smaller output
		minify: 'esbuild',
	},
	server: {
		open: '/examples/basic.html', // Auto-open examples on dev server start
		port: 5173,
		headers: {
			'Cross-Origin-Opener-Policy': 'same-origin',
			'Cross-Origin-Embedder-Policy': 'require-corp',
		},
	},
	optimizeDeps: {
		exclude: ['@sqlite.org/sqlite-wasm'], // Don't pre-bundle SQLite WASM
	},
	worker: {
		format: 'es',
		rollupOptions: {
			output: {
				// Force everything into a single chunk for the worker
				inlineDynamicImports: true,
			},
		},
	},
});
